# Generated by Django 3.2.13 on 2022-06-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_applications'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applications',
            unique_together={('applicant', 'job')},
        ),
    ]
