# Generated by Django 3.2.13 on 2022-07-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20220616_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('Applied', 'applied'), ('Accepted', 'accepted'), ('Rejected', 'rejected'), ('Pending', 'pending'), ('Cancelled', 'cancelled')], default='Applied', max_length=120),
        ),
    ]
