# Generated by Django 3.2.13 on 2022-06-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_companyprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(null=True, upload_to='company_profile'),
        ),
    ]
