# Generated by Django 3.2.13 on 2022-07-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='files/profile_pic')),
                ('resume', models.FileField(null=True, upload_to='files/resumes_or_cvs')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('qualification', models.CharField(max_length=120)),
                ('skills', models.CharField(max_length=120)),
                ('experience', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
