# Generated by Django 3.2.13 on 2022-06-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_candidateprofiles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofiles',
            name='resume',
            field=models.FileField(null=True, upload_to='files/resumes_or_cvs'),
        ),
    ]
