# Generated by Django 3.2.13 on 2022-07-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidateprofiles_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofiles',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
